# This is a basic workflow to help you get started with Actions

# Based on Kade engine ci
# Made by luckydog7 for https://github.com/luckydog7/Funkin-android

name: Android Build CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.5
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %HAXELIB_ROOT%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup Android SDL
        uses: libsdl-org/setup-sdl@v1
        id: sdl
        with:
          install-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
          
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
 
      # Runs a set of commands using the runners shell
      - name: Install Libraries
        run: |
          mkdir -p "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%" 
          haxelib install lime 8.1.3 --quiet
          haxelib install flixel 5.8.0 --quiet
          haxelib install openfl 9.3.4 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install hxcpp-debug-server 1.2.4 --quiet
          haxelib git polymod https://github.com/swordcube/scriptless-polymod.git  --quiet
          haxelib install flixel-text-input 2.0.2 --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git --quiet
          haxelib git tjson http s://github.com/EliteMasterEric/TJSON.git  --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved.git --quiet
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git --quiet
          haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel.git --skip-dependencies
          haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git --skip-dependencies
          haxelib install hxvlc 1.8.0 --quiet
          haxelib install hscript 2.5.0 --quiet
          haxelib git hxcpp  https://github.com/mcagabe19-stuff/hxcpp.git --quiet
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib list
          
      - name: Compile
        run: haxelib run lime build android -Dci
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export/release/android/bin/app/build/outputs/apk/debug 
