name: androidBuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    strategy:
      matrix:
        storage-type: [EXTERNAL]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Restore Previous Cache
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.3 --quiet
          haxelib install flixel 5.8.0 --quiet
          haxelib install openfl 9.3.4 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install hxcpp-debug-server 1.2.4 --quiet
          haxelib git polymod https://github.com/swordcube/scriptless-polymod.git  --quiet
          haxelib install flixel-text-input 2.0.2 --quiet
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit.git --quiet
          haxelib git tjson http s://github.com/EliteMasterEric/TJSON.git  --quiet
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved.git --quiet
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc.git --quiet
          haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel.git --skip-dependencies
          haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git --skip-dependencies
          haxelib install hxvlc 1.8.0 --quiet
          haxelib install hscript 2.5.0 --quiet
          haxelib git hxcpp  https://github.com/mcagabe19-stuff/hxcpp.git --quiet
          
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          
      - name: Compile
        run: haxelib run lime build android -D ${{ matrix.storage-type }} -final
        env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk